export const IMAGE_TYPES = ['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif']
export const VIDEO_TYPES = ['mp4', 'video/ogg', 'webm', 'quicktime']
export const AUDIO_TYPES = ['mp3', 'audio/ogg', 'wav', 'mpeg']
export const APPLICATION_TYPES = ['exe', 'rpm', 'app','jar']
export const PACKAGE_TYPES = ['rar', 'zip', '7z','tar','iso','gz']
